// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AzureExplorer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AzureExplorerToolWindowString = "d4b65484-2b5e-4e73-b5a0-9c9f91e1dc21";
        public static Guid AzureExplorerToolWindow = new Guid(AzureExplorerToolWindowString);

        public const string AzureExplorerString = "5e5465aa-805e-4395-b20d-a439f7c92ca1";
        public static Guid AzureExplorer = new Guid(AzureExplorerString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowToolbar = 0x0010;
        public const int SubscriptionContextMenu = 0x0020;
        public const int ResourceGroupContextMenu = 0x0021;
        public const int AppServiceContextMenu = 0x0022;
        public const int AppServicePlanContextMenu = 0x0025;
        public const int AppServicesCategoryContextMenu = 0x0026;
        public const int AppServicePlansCategoryContextMenu = 0x0027;
        public const int FrontDoorContextMenu = 0x0028;
        public const int FrontDoorsCategoryContextMenu = 0x0029;
        public const int KeyVaultContextMenu = 0x0050;
        public const int KeyVaultsCategoryContextMenu = 0x0051;
        public const int StorageAccountContextMenu = 0x0160;
        public const int StorageAccountsCategoryContextMenu = 0x0161;
        public const int FunctionAppContextMenu = 0x0170;
        public const int FunctionAppsCategoryContextMenu = 0x0171;
        public const int SqlServerContextMenu = 0x0180;
        public const int SqlServersCategoryContextMenu = 0x0181;
        public const int SqlDatabaseContextMenu = 0x0182;
        public const int VirtualMachineContextMenu = 0x01A0;
        public const int VirtualMachinesCategoryContextMenu = 0x01A1;
        public const int BlobContainerContextMenu = 0x0190;
        public const int BlobContextMenu = 0x0191;
        public const int BlobFolderContextMenu = 0x0192;
        public const int SecretContextMenu = 0x0055;
        public const int TenantContextMenu = 0x002A;
        public const int AccountContextMenu = 0x002B;
        public const int FileContextMenu = 0x002C;
        public const int FolderContextMenu = 0x002D;
        public const int ViewMenuGroup = 0x0030;
        public const int ToolbarGroup = 0x0031;
        public const int SubscriptionContextMenuGroup = 0x0040;
        public const int ResourceGroupContextMenuGroup = 0x0041;
        public const int AppServicePlanContextMenuGroup = 0x0048;
        public const int AppServicesCategoryContextMenuGroup = 0x0049;
        public const int AppServicePlansCategoryContextMenuGroup = 0x004A;
        public const int FrontDoorBrowseGroup = 0x004B;
        public const int FrontDoorRefreshGroup = 0x004C;
        public const int FrontDoorsCategoryContextMenuGroup = 0x004D;
        public const int KeyVaultBrowseGroup = 0x0052;
        public const int KeyVaultActionsGroup = 0x0056;
        public const int KeyVaultRefreshGroup = 0x0053;
        public const int KeyVaultsCategoryContextMenuGroup = 0x0054;
        public const int StorageAccountActionsGroup = 0x0162;
        public const int StorageAccountRefreshGroup = 0x0163;
        public const int StorageAccountsCategoryContextMenuGroup = 0x0164;
        public const int FunctionAppBrowseGroup = 0x0172;
        public const int FunctionAppActionsGroup = 0x0173;
        public const int FunctionAppRefreshGroup = 0x0174;
        public const int FunctionAppsCategoryContextMenuGroup = 0x0175;
        public const int SqlServerActionsGroup = 0x0183;
        public const int SqlServerRefreshGroup = 0x0184;
        public const int SqlServersCategoryContextMenuGroup = 0x0185;
        public const int SqlDatabaseActionsGroup = 0x0186;
        public const int VirtualMachineConnectGroup = 0x01A2;
        public const int VirtualMachineActionsGroup = 0x01A3;
        public const int VirtualMachineRefreshGroup = 0x01A4;
        public const int VirtualMachinesCategoryContextMenuGroup = 0x01A5;
        public const int BlobContainerActionsGroup = 0x0193;
        public const int BlobContainerRefreshGroup = 0x0194;
        public const int BlobActionsGroup = 0x0195;
        public const int BlobDeleteGroup = 0x0196;
        public const int BlobFolderRefreshGroup = 0x0197;
        public const int SecretActionsGroup = 0x0057;
        public const int SecretDeleteGroup = 0x0058;
        public const int TenantContextMenuGroup = 0x004E;
        public const int AccountContextMenuGroup = 0x004F;
        public const int FileContextMenuGroup = 0x0060;
        public const int FolderContextMenuGroup = 0x0061;
        public const int AppServiceBrowseGroup = 0x0042;
        public const int AppServiceActionsGroup = 0x0043;
        public const int AppServiceDiagnosticsGroup = 0x0045;
        public const int StreamingLogsFlyout = 0x0023;
        public const int StreamingLogsGroup = 0x0046;
        public const int AppServiceRefreshGroup = 0x0044;
        public const int LogWindowToolbar = 0x0024;
        public const int LogWindowToolbarGroup = 0x0047;
        public const int ShowExplorerWindow = 0x0100;
        public const int SignIn = 0x0101;
        public const int Refresh = 0x0102;
        public const int RefreshSubscription = 0x0103;
        public const int RefreshResourceGroup = 0x0104;
        public const int RefreshTenant = 0x0105;
        public const int SignOutAccount = 0x0106;
        public const int RefreshAccount = 0x0107;
        public const int BrowseSite = 0x0110;
        public const int StartAppService = 0x0111;
        public const int StopAppService = 0x0112;
        public const int RestartAppService = 0x0113;
        public const int RefreshAppService = 0x0114;
        public const int OpenPortal = 0x0115;
        public const int OpenKudu = 0x0116;
        public const int StreamLogs = 0x0117;
        public const int StreamHttpLogs = 0x0118;
        public const int DisconnectLogStream = 0x0119;
        public const int ManageAppSettings = 0x011A;
        public const int DownloadPublishProfile = 0x011B;
        public const int RefreshNode = 0x011C;
        public const int OpenAppServicePlanPortal = 0x0120;
        public const int RefreshAppServicesCategory = 0x0121;
        public const int RefreshAppServicePlansCategory = 0x0122;
        public const int BrowseFrontDoor = 0x0130;
        public const int OpenFrontDoorPortal = 0x0131;
        public const int RefreshFrontDoor = 0x0132;
        public const int RefreshFrontDoorsCategory = 0x0133;
        public const int OpenKeyVaultPortal = 0x0140;
        public const int RefreshKeyVault = 0x0141;
        public const int RefreshKeyVaultsCategory = 0x0142;
        public const int CopyVaultUri = 0x0143;
        public const int AddSecret = 0x0144;
        public const int CopySecretValue = 0x0145;
        public const int UpdateSecretValue = 0x0146;
        public const int DeleteSecret = 0x0147;
        public const int DeleteFile = 0x0148;
        public const int DeleteFolder = 0x0149;
        public const int OpenInPortal = 0x0150;
        public const int CopyStorageConnectionString = 0x0165;
        public const int CopySqlConnectionString = 0x0187;
        public const int CopyBlobUrl = 0x0198;
        public const int DeleteBlob = 0x0199;
        public const int DownloadBlob = 0x019A;
        public const int UploadBlob = 0x019B;
        public const int StartVm = 0x01B0;
        public const int StopVm = 0x01B1;
        public const int RestartVm = 0x01B2;
        public const int CopyVmIpAddress = 0x01B3;
        public const int ConnectRdp = 0x01B4;
        public const int ConnectSsh = 0x01B5;
    }
}
