// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AzureExplorer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AzureExplorerString = "5e5465aa-805e-4395-b20d-a439f7c92ca1";
        public static Guid AzureExplorer = new Guid(AzureExplorerString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowToolbar = 0x0010;
        public const int SubscriptionContextMenu = 0x0020;
        public const int ResourceGroupContextMenu = 0x0021;
        public const int AppServiceContextMenu = 0x0022;
        public const int AppServicePlanContextMenu = 0x0025;
        public const int AppServicesCategoryContextMenu = 0x0026;
        public const int AppServicePlansCategoryContextMenu = 0x0027;
        public const int FrontDoorContextMenu = 0x0028;
        public const int FrontDoorsCategoryContextMenu = 0x0029;
        public const int KeyVaultContextMenu = 0x0050;
        public const int KeyVaultsCategoryContextMenu = 0x0051;
        public const int TenantContextMenu = 0x002A;
        public const int AccountContextMenu = 0x002B;
        public const int ViewMenuGroup = 0x0030;
        public const int ToolbarGroup = 0x0031;
        public const int SubscriptionContextMenuGroup = 0x0040;
        public const int ResourceGroupContextMenuGroup = 0x0041;
        public const int AppServicePlanContextMenuGroup = 0x0048;
        public const int AppServicesCategoryContextMenuGroup = 0x0049;
        public const int AppServicePlansCategoryContextMenuGroup = 0x004A;
        public const int FrontDoorBrowseGroup = 0x004B;
        public const int FrontDoorRefreshGroup = 0x004C;
        public const int FrontDoorsCategoryContextMenuGroup = 0x004D;
        public const int KeyVaultBrowseGroup = 0x0052;
        public const int KeyVaultActionsGroup = 0x0056;
        public const int KeyVaultRefreshGroup = 0x0053;
        public const int KeyVaultsCategoryContextMenuGroup = 0x0054;
        public const int TenantContextMenuGroup = 0x004E;
        public const int AccountContextMenuGroup = 0x004F;
        public const int AppServiceBrowseGroup = 0x0042;
        public const int AppServiceActionsGroup = 0x0043;
        public const int AppServiceDiagnosticsGroup = 0x0045;
        public const int StreamingLogsFlyout = 0x0023;
        public const int StreamingLogsGroup = 0x0046;
        public const int AppServiceRefreshGroup = 0x0044;
        public const int LogWindowToolbar = 0x0024;
        public const int LogWindowToolbarGroup = 0x0047;
        public const int ShowExplorerWindow = 0x0100;
        public const int SignIn = 0x0101;
        public const int Refresh = 0x0102;
        public const int RefreshSubscription = 0x0103;
        public const int RefreshResourceGroup = 0x0104;
        public const int RefreshTenant = 0x0105;
        public const int SignOutAccount = 0x0106;
        public const int RefreshAccount = 0x0107;
        public const int BrowseSite = 0x0110;
        public const int StartAppService = 0x0111;
        public const int StopAppService = 0x0112;
        public const int RestartAppService = 0x0113;
        public const int RefreshAppService = 0x0114;
        public const int OpenPortal = 0x0115;
        public const int OpenKudu = 0x0116;
        public const int StreamLogs = 0x0117;
        public const int StreamHttpLogs = 0x0118;
        public const int DisconnectLogStream = 0x0119;
        public const int OpenAppServicePlanPortal = 0x0120;
        public const int RefreshAppServicesCategory = 0x0121;
        public const int RefreshAppServicePlansCategory = 0x0122;
        public const int BrowseFrontDoor = 0x0130;
        public const int OpenFrontDoorPortal = 0x0131;
        public const int RefreshFrontDoor = 0x0132;
        public const int RefreshFrontDoorsCategory = 0x0133;
        public const int OpenKeyVaultPortal = 0x0140;
        public const int RefreshKeyVault = 0x0141;
        public const int RefreshKeyVaultsCategory = 0x0142;
        public const int CopyVaultUri = 0x0143;
        public const int AddSecret = 0x0144;
        public const int CopySecretValue = 0x0145;
        public const int UpdateSecretValue = 0x0146;
        public const int DeleteSecret = 0x0147;
        public const int OpenInPortal = 0x0150;
        public const int SecretContextMenu = 0x0055;
        public const int SecretActionsGroup = 0x0057;
        public const int SecretDeleteGroup = 0x0058;
    }
}
