// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AzureExplorer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AzureExplorerString = "5e5465aa-805e-4395-b20d-a439f7c92ca1";
        public static Guid AzureExplorer = new Guid(AzureExplorerString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowToolbar = 0x0010;
        public const int SubscriptionContextMenu = 0x0020;
        public const int ResourceGroupContextMenu = 0x0021;
        public const int AppServiceContextMenu = 0x0022;
        public const int ViewMenuGroup = 0x0030;
        public const int ToolbarGroup = 0x0031;
        public const int SubscriptionContextMenuGroup = 0x0040;
        public const int ResourceGroupContextMenuGroup = 0x0041;
        public const int AppServiceBrowseGroup = 0x0042;
        public const int AppServiceActionsGroup = 0x0043;
        public const int AppServiceDiagnosticsGroup = 0x0045;
        public const int StreamingLogsFlyout = 0x0023;
        public const int StreamingLogsGroup = 0x0046;
        public const int AppServiceRefreshGroup = 0x0044;
        public const int ShowExplorerWindow = 0x0100;
        public const int SignIn = 0x0101;
        public const int Refresh = 0x0102;
        public const int RefreshSubscription = 0x0103;
        public const int RefreshResourceGroup = 0x0104;
        public const int BrowseSite = 0x0110;
        public const int StartAppService = 0x0111;
        public const int StopAppService = 0x0112;
        public const int RestartAppService = 0x0113;
        public const int RefreshAppService = 0x0114;
        public const int OpenPortal = 0x0115;
        public const int OpenKudu = 0x0116;
        public const int StreamLogs = 0x0117;
        public const int StreamHttpLogs = 0x0118;
    }
}
